siteDomain = "http://www.piedcode.com"
siteTitle = "PiedCode"
siteDesc = "Blog about the daily challenges and discoveries of an aspiring web developer"
siteAuthor = "Simon Reinsperger"
siteAuthorEmail = "reinsperger.smn@gmail.com"
siteAuthorUrl = "http://www.piedcode.com"

useGravatar = true
gravatarHash = '40e23134e2c0a3d11251c21fdcb813d6'

useDisqus = true
disqusShortname = "piedcode"

siteYouTubeUrl = "https://www.youtube.com/channel/UCTi2gmJFc_cGwuo8Igvsmxw"
siteTwitterUrl = "https://twitter.com/simon_rsp"
siteGithubUrl = "https://github.com/abisz"
siteEmailUrl = "mailto:reinsperger.smn@gmail.com"
siteRssUrl = "/rss.xml"
siteCodePenUrl = "http://codepen.io/abisz/"

linkPrefix = "/mt-disqus-gatsby"

googleAnalyticsId = "UA-73061728-1"

buildSPA = true